[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/exp1.1/1.1.html"
  status = 200

[[redirects]]
  from = "/EXP1.1"
  to = "/EXP1.1/EXP1.1.HTML"
  status = 200

[[redirects]]
  from = "/EXP1.2"
  to = "/EXP1.2/1.3.html"
  status = 200

[[redirects]]
  from = "/EXP1.3"
  to = "EXP1.3/EXP1.3.html"
  status = 200
